### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by TehChozinOne** [d-haxton/HaxtonBot#12]
Unhandled Exception: System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at PokemonGo.Haxton.Bot.Login.PoGoLogin.<OnGoogleDeviceCode>d__4.MoveNext() in K:\Games\PGO Bot\Haxton 25\PokemonGo.Haxton.Bot\Login\PoGoLogin.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

I've Tried changing coord between "." and "," still same error

**Comment by nthacks** [comment]
Unhandled Exception:
Unhandled Exception: System.InvalidOperationException: Handler did not return a response message.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiBaseRpc.<PostProtoPayload>d__8`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiBaseRpc.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiInventory.<EvolvePokemon>d__4.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiInventory.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Inventory.PoGoInventory.<EvolvePokemon>d__36.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Inventory\PoGoInventory.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Bot.PoGoBot.<<EvolvePokemonTask>b__28_0>d.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Bot\PoGoBot.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()



Unhandled Exception: System.InvalidOperationException: Handler did not return a response message.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiBaseRpc.<PostProtoPayload>d__8`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiBaseRpc.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiInventory.<EvolvePokemon>d__4.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiInventory.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Inventory.PoGoInventory.<EvolvePokemon>d__36.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Inventory\PoGoInventory.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Bot.PoGoBot.<<EvolvePokemonTask>b__28_0>d.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Bot\PoGoBot.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()Unhandled Exception:

Unhandled Exception: Unhandled Exception: System.InvalidOperationException: Handler did not return a response message.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiBaseRpc.<PostProtoPayload>d__8`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiBaseRpc.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiInventory.<EvolvePokemon>d__4.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiInventory.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Inventory.PoGoInventory.<EvolvePokemon>d__36.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Inventory\PoGoInventory.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Bot.PoGoBot.<<EvolvePokemonTask>b__28_0>d.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Bot\PoGoBot.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()System.InvalidOperationException: Handler did not return a response message.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiBaseRpc.<PostProtoPayload>d__8`2.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiBaseRpc.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.ApiProvider.ApiInventory.<EvolvePokemon>d__4.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\ApiProvider\ApiInventory.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Inventory.PoGoInventory.<EvolvePokemon>d__36.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Inventory\PoGoInventory.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.Haxton.Bot.Bot.PoGoBot.<<EvolvePokemonTask>b__28_0>d.MoveNext() in C:\Users\nisch\Downloads\pkgo\HaxtonBot-master\PokemonGo.Haxton.Bot\Bot\PoGoBot.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by oomps** [comment]
I'm receiving the same error.

**Comment by zsinghua** [comment]
Same error here for google sign in, while different error for PTC sign in.

**Comment by Briskey** [comment]
Same error as OP.
Unhandled Exception: System.InvalidOperationException: Cannot start process because a file name has not been provided.
Old version works fine. (from earlier today)
