### ISSUE TITLE
Google Login Error

### ISSUE THREAD

**Issue by pondtroid** [d-haxton/HaxtonBot#13]
log show this after start

20160728141203 Logging in with account type: Google

Unhandled Exception: System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at PokemonGo.Haxton.Bot.Login.PoGoLogin.<OnGoogleDeviceCode>d__4.MoveNext() in C:\Users\User\Desktop\Haxton\PokemonGo.Haxton.Bot\Login\PoGoLogin.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Press any key to continue . . .

**Comment by icdance** [comment]
Google token server down, all new account cannot be authed

**Comment by d-haxton** [comment]
Use google email/password
